# Meta Data for SEO

## Homepage
title = "Ropecamp 2022"
titleSeparator = "-"
titleAddition = "How to survive Rogue Rope Camp"
description = "Find all info here."

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "roguerope"
twitterCreator = "roguerope"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/roguerope"
## schemaLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaGitHub = "https://github.com/RogueRope"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = true

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://gohugo.io/\">Hugo</a> and <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/\">Doks</a>. Made with &#10084; in Ghent."

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/RogueRope/docs"
editPage = false

[options]
  lazySizes = true
  clipBoard = false
  instantPage = false
  flexSearch = false
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
