baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Bottoms Up! - Rope Gathering'
theme = 'hugo-book'

[params]
  BookTheme = "auto"
  BookShowToc = true
  BookShowBreadcrumbs = true
  BookShowReadingTime = true
  BookSearch = true
  BookSearchPlaceholder = "Search gathering info..."
  BookMenuBundle = true
  BookCollapseSection = true

[[menu.before]]
  identifier = "home"
  name = "üè† Home"
  url = "/"
  weight = 1

[[menu.after]]
  identifier = "contact"
  name = "‚úâÔ∏è Contact"
  url = "mailto:info@roguerope.be"
  weight = 1

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[outputs]
  home = ["HTML", "RSS", "JSON"]
