baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Bottoms Up!'
theme = 'hugo-book'
ignoreLogs = ['warning-goldmark-raw-html', 'warning-no-layout-for-kind']

[params]
  BookTheme = "auto"
  BookShowToc = true
  BookShowBreadcrumbs = true
  BookShowReadingTime = true
  BookSearch = true
  BookSearchPlaceholder = "Search gathering info..."
  BookMenuBundle = true
  BookCollapseSection = true

[[menu.before]]
  identifier = "home"
  name = "üè† Home"
  url = "/"
  weight = 1

[[menu.after]]
  identifier = "contact"
  name = "‚úâÔ∏è Contact"
  url = "/docs/contact"
  weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[outputs]
  home = ["HTML", "RSS"]
