[[main]]
  name = "Philosophy"
  weight = 2
  url = "concept"

[[main]]
  name = "Details"
  weight = 3
  url = "practical"

[[main]]
  name = "Care"
  weight = 4
  url = "wellbeing"


[[main]]
  name = "Contact"
  weight = 6
  url = "contact"
